---
title: Music extension कसा जोडावा
hero_image: images/banner.png
description: generic-scratch3-add-music-extension description
version: 0
listed: false
copyedit: false
last_tested: "२०१८-११-२६"
steps:
  - 
    title: परिचय
