---
title: संगीत विस्तार कसा जोडावा
hero_image: images/banner.png
description: generic-scratch3-add-music-extension वर्णन
version: 0
listed: false
copyedit: false
last_tested: "२०१८-११-२६"
steps:
  - title: परिचय
