---
title: Music ఎక్స్‌టెన్షన్ ని ఎలా జోడించాలి
hero_image: images/banner.png
description: generic-scratch3-add-music-extension వివరణ
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: పరిచయం
