---
title: Kuinka lis채t채 Musiikkilaajennus
hero_image: images/banner.png
description: yleinen-scratch3-lis채채-musiikkilaajennus kuvaus
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: Esittely
