---
title: Cómo añadir la extensión Música
hero_image: images/banner.png
description: descripción de generic-scratch3-add-music-extension
version: 4
listed: false
copyedit: false
last_tested: "2018-26-01"
steps:
  - 
    title: Introducción
