---
title: Cum să adaugi extensia Muzică
hero_image: images/banner.png
description: generic-scratch3-add-music-extension description
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: Introducere
