---
title: Como adicionar a extensão Música
hero_image: images/banner.png
description: generic-scratch3-add-music-extension descrição
version: 4
listed: false
copyedit: false
last_tested: "26-11-2018"
steps:
  - 
    title: Introdução
