---
title: Como adicionar a extensão Música
hero_image: images/banner.png
description: descrição generic-scratch3-add-music-extension
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Introdução
