---
title: Cara menambahkan ekstensi Musik
hero_image: images/banner.png
description: Menambahkan ekstensi musik ke proyek scratch
version: 4
listed: false
copyedit: false
last_tested: "2018-26-01"
steps:
  - 
    title: Pengantar
