---
title: How to add the Music extension
hero_image: images/banner.png
description: generic-scratch3-add-music-extension description
version: 4
listed: false
copyedit: false
last_tested: "2018-26-01"
steps:
  - 
    title: Introduction
