---
title: Cómo añadir la extensión Música
hero_image: images/banner.png
description: descripción genérica extensión-agregar-musica-scratch3
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Introducción
