---
title: Comment ajouter l'extension Musique
hero_image: images/banner.png
description: description générique de scratch3-ajouter-extension musique
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Introduction
