---
title: Come aggiungere l'estensione Musica
hero_image: images/banner.png
description: generic-scratch3-add-music-extension descrizione
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - 
    title: Introduzione
